// Generated by CoffeeScript 2.3.2
(function() {
  var ALLOWED_TAGS, AttValSE, CDATA_CE, CommentCE, DT_IdentSE, DT_ItemSE, DeclCE, DocTypeCE, EXCLUDED_TAGS, ElemTagCE, EndTagCE, MarkupDeclCE, MarkupSPE, Name, NameChar, NameStrt, PI_CE, PI_Tail, QuoteSE, S, S1, SELF_CLOSING_TAGS, ShallowParse, TextSE, Until2Hyphens, UntilHyphen, UntilQMs, UntilRSBs, XMLParse, XML_SPE, XRegExp, _linkify, close, expressionParse, isClose, isOpen, isSelfClose, isWord, isntWord, linkify, makeTag, tagName, tokenize_text, try_match;

  XRegExp = require('xregexp');

  // REX/Javascript 1.0
  // Robert D. Cameron "REX: XML Shallow Parsing with Regular Expressions",
  // Technical Report TR 1998-17, School of Computing Science, Simon Fraser
  // University, November, 1998.
  // Copyright (c) 1998, Robert D. Cameron.
  // The following code may be freely used and distributed provided that
  // this copyright and citation notice remains intact and that modifications
  // or additions are clearly identified.
  TextSE = '[^<]+';

  UntilHyphen = '[^-]*-';

  Until2Hyphens = UntilHyphen + '([^-]' + UntilHyphen + ')*-';

  CommentCE = Until2Hyphens + '>?';

  UntilRSBs = '[^]]*]([^]]+])*]+';

  CDATA_CE = UntilRSBs + '([^]>]' + UntilRSBs + ')*>';

  S = '[ \\n\\t\\r]+';

  NameStrt = '[A-Za-z_:]|[^\\x00-\\x7F]';

  NameChar = '[A-Za-z0-9_:.-]|[^\\x00-\\x7F]';

  Name = '(' + NameStrt + ')(' + NameChar + ')*';

  QuoteSE = '"[^"]' + '*' + '"' + '|\'[^\']*\'';

  DT_IdentSE = S + Name + '(' + S + '(' + Name + '|' + QuoteSE + '))*';

  MarkupDeclCE = '([^]"\'><]+|' + QuoteSE + ')*>';

  S1 = '[\\n\\r\\t ]';

  UntilQMs = '[^?]*\\?+';

  PI_Tail = '\\?>|' + S1 + UntilQMs + '([^>?]' + UntilQMs + ')*>';

  DT_ItemSE = '<(!(--' + Until2Hyphens + '>|[^-]' + MarkupDeclCE + ')|\\?' + Name + '(' + PI_Tail + '))|%' + Name + ';|' + S;

  DocTypeCE = DT_IdentSE + '(' + S + ')?(\\[(' + DT_ItemSE + ')*](' + S + ')?)?>?';

  DeclCE = '--(' + CommentCE + ')?|\\[CDATA\\[(' + CDATA_CE + ')?|DOCTYPE(' + DocTypeCE + ')?';

  PI_CE = Name + '(' + PI_Tail + ')?';

  EndTagCE = Name + '(' + S + ')?>?';

  AttValSE = '"[^<"]' + '*' + '"' + '|\'[^<\']*\'';

  ElemTagCE = Name + '(' + S + Name + '(' + S + ')?=(' + S + ')?(' + AttValSE + '))*(' + S + ')?/?>?';

  MarkupSPE = '<(!(' + DeclCE + ')?|\\?(' + PI_CE + ')?|/(' + EndTagCE + ')?|(' + ElemTagCE + ')?)';

  XML_SPE = TextSE + '|' + MarkupSPE;

  ShallowParse = function(XMLdoc) {
    return XMLdoc.match(new RegExp(XML_SPE, 'g'));
  };

  // REX END - thank you Robert! Awesome...

  // maybe this is a better way to think about it...
  // don't hyperlink if parent stack contain any of
  // these?
  EXCLUDED_TAGS = {
    a: {
      a: true
    },
    pre: {
      img: true,
      object: true,
      big: true,
      small: true,
      sub: true,
      sup: true
    },
    button: {
      input: true,
      select: true,
      textarea: true,
      label: true,
      button: true,
      form: true,
      fieldset: true,
      iframe: true,
      isindex: true
    },
    label: {
      label: true
    },
    form: {
      form: true
    }
  };

  SELF_CLOSING_TAGS = {
    area: true,
    base: true,
    br: true,
    col: true,
    embed: true,
    hr: true,
    img: true,
    input: true,
    link: true,
    meta: true,
    param: true,
    source: true,
    track: true,
    wbr: true,
    command: true,
    keygen: true,
    menuitem: true
  };

  ALLOWED_TAGS = {
    br: true,
    span: true,
    bdo: true,
    map: true,
    object: true,
    img: true,
    tt: true,
    i: true,
    b: true,
    big: true,
    small: true,
    ins: true,
    del: true,
    script: true,
    input: true,
    select: true,
    textarea: true,
    label: true,
    button: true,
    em: true,
    strong: true,
    dfn: true,
    code: true,
    q: true,
    samp: true,
    kbd: true,
    var: true,
    cite: true,
    abbr: true,
    acronym: true,
    sub: true,
    sup: true
  };

  XMLParse = function(xml_doc) {
    return xml_doc.match(new RegExp(XML_SPE, "g"));
  };

  expressionParse = function(expression) {
    return expression.match(XRegExp("[\\pL\\pN]+", "g"));
  };

  makeTag = function(tag, opts) {
    var k, opt_array, v;
    if (!opts || Object.keys(opts).length === 0) {
      return '<' + tag + '>';
    }
    opt_array = [];
    for (k in opts) {
      v = opts[k];
      opt_array.push(k + '="' + v + '"');
    }
    return '<' + tag + ' ' + opt_array.join(' ') + '>';
  };

  isOpen = function(item) {
    if (!item) {
      return false;
    }
    if (typeof item !== 'string') {
      return false;
    }
    if (!item.match(/^</)) {
      return false;
    }
    if (item.match(/^<\!/)) {
      return false;
    }
    if (item.match(/^<\//)) {
      return false;
    }
    if (item.match(/\/>$/)) {
      return false;
    }
    if (item.match(/^<\?/)) {
      return false;
    }
    if (item.match(/^</)) {
      return true;
    }
    return false;
  };

  isClose = function(item) {
    if (!item) {
      return false;
    }
    if (typeof item !== 'string') {
      return false;
    }
    if (!item.match(/^</)) {
      return false;
    }
    if (item.match(/^<\!/)) {
      return false;
    }
    if (item.match(/\/>$/)) {
      return false;
    }
    if (item.match(/^<\//)) {
      return true;
    }
    return false;
    return false;
  };

  isSelfClose = function(item, selfclose) {
    if (isOpen(item) && selfclose[tagName(item)]) {
      return true;
    }
    if (!item) {
      return false;
    }
    if (typeof item !== 'string') {
      return false;
    }
    if (!item.match(/^</)) {
      return false;
    }
    if (item.match(/^<\!/)) {
      return false;
    }
    if (item.match(/^<\//)) {
      return false;
    }
    if (item.match(/\/>$/) && item.match(/^</)) {
      return false;
    }
    return false;
  };

  isWord = function(item) {
    return item.match(XRegExp("^[\\pL\\pN]+$"));
  };

  isntWord = function(item) {
    return item.match(XRegExp("^[^\\pL\\pN]+$"));
  };

  tagName = function(item) {
    var match;
    match = String(item).match(/([A-Za-z_][A-Za-z0-9_.]*)/);
    if (match) {
      return match[0];
    } else {
      return '__weird_stuff_that_fails_test_07__';
    }
  };

  close = function(item) {
    return `</${tagName(item)}>`;
  };

  try_match = function(xml, x_init, expression, tag, attributes, stack_parent, opts) {
    var FSM, forbidden, forbidden_tag, j, l, len, len1, result, ret_val, stack_post, stack_pre, stacked_tag, state, t, x;
    // if this tag is excluded
    if (opts.excluded) {
      forbidden = Object.keys(opts.excluded);
// so we take all forbidden tags...
      for (j = 0, len = forbidden.length; j < len; j++) {
        forbidden_tag = forbidden[j];
// if any of these is in the parent stack, we can't match.
        for (l = 0, len1 = stack_parent.length; l < len1; l++) {
          stacked_tag = stack_parent[l];
          if (tagName(stacked_tag) === forbidden_tag) {
            return null;
          }
        }
      }
    }
    x = x_init;
    t = 0;
    ret_val = null;
    result = [];
    stack_pre = null;
    stack_post = null;
    state = 'ROUTE';
    FSM = {
      OPENTAG: function() {
        var item;
        item = xml[x];
        if (opts.allowed[tagName(item)]) {
          stack_post || (stack_post = []);
          stack_post.push(item);
          result.push(item);
          x++;
          return state = 'ROUTE';
        } else {
          return state = 'FAIL';
        }
      },
      CLOSETAG: function() {
        var item;
        item = xml[x];
        if (opts.allowed[tagName(item)]) {
          if (stack_post) {
            stack_post.pop();
          } else {
            stack_pre || (stack_pre = []);
            stack_pre.push(item);
          }
          result.push(item);
          x++;
          return state = 'ROUTE';
        } else {
          return state = 'FAIL';
        }
      },
      OTHER: function() {
        var item;
        item = xml[x];
        result.push(item);
        x++;
        return state = 'ROUTE';
      },
      WORD: function() {
        var item;
        item = xml[x];
        if (item.toLowerCase() === expression[t].toLowerCase()) {
          result.push(item);
          x++;
          t++;
          return state = 'ROUTE';
        } else {
          return state = 'FAIL';
        }
      },
      SUCCESS: function() {
        var closetag, inner_body, inner_head, inner_tail, offset, opentag, outer_head, outer_tail;
        xml[x_init];
        offset = x - x_init;
        stack_pre || (stack_pre = []);
        stack_post || (stack_post = []);
        if (stack_pre.length) {
          outer_head = stack_pre.join('');
        } else {
          outer_head = '';
        }
        opentag = makeTag(tag, attributes);
        if (stack_pre.length) {
          inner_head = stack_parent.slice(-stack_pre.length).join('');
        } else {
          inner_head = '';
        }
        inner_body = result.join('');
        if (stack_post.length) {
          inner_tail = stack_post.reverse().map(function(item) {
            return close(item);
          }).join('');
        } else {
          inner_tail = '';
        }
        closetag = '</' + tag + '>';
        if (stack_post.length) {
          outer_tail = stack_post.join('');
        } else {
          outer_tail = '';
        }
        result = outer_head + opentag + inner_head + inner_body + inner_tail + closetag + outer_tail;
        // modify the xml array with the new element
        xml.splice(x_init, offset, result);
        ret_val = x + 1;
        return state = 'STOP';
      },
      FAIL: function() {
        ret_val = null;
        return state = 'STOP';
      },
      ROUTE: function() {
        var item;
        if (t === expression.length) {
          state = 'SUCCESS';
          return;
        }
        if (xml.length === 0) {
          state = 'FAIL';
          return;
        }
        if (isSelfClose(xml[x], opts.selfclose)) {
          state = 'OTHER';
          return;
        }
        if (isOpen(xml[x])) {
          state = 'OPENTAG';
          return;
        }
        if (isClose(xml[x])) {
          item = xml[x];
          if (opts.allowed[tagName(item)]) {
            state = 'CLOSETAG';
            return;
          } else {
            state = 'FAIL';
            return;
          }
        }
        if (isWord(xml[x])) {
          state = 'WORD';
          return;
        }
        if (isntWord(xml[x])) {
          state = 'OTHER';
          return;
        }
        console.error("Unexpected state. Please file a bug report!");
        return state = 'FAIL';
      }
    };
    // when we're done, join all the XML bits to compute the result
    while (state !== 'STOP') {
      if (FSM[state]) {
        FSM[state]();
      } else {
        console.log(state, " not implemented...");
        process.exit(0);
      }
    }
    return ret_val;
  };

  _linkify = function(xml, items, opts) {
    var FSM, e, i, prev_state, stack, state, x;
    x = 0; // xml index
    i = 0; // items index
    e = 0; // item expression index
    stack = [];
    state = 'ROUTE';
    FSM = {
      TRY_MATCH: function() {
        var _opts, attributes, item, result;
        item = items[i];
        if (item) {
          attributes = item.attributes || {};
          _opts = {
            selfclose: item.selfclose || opts.selfclose,
            allowed: item.allowed || opts.allowed
          };
          if (item.excluded) {
            _opts.excluded = item.excluded || {};
          } else {
            _opts.excluded = opts.excluded[item.tag] || {};
          }
          result = try_match(xml, x, expressionParse(item.expression), item.tag, item.attributes, stack, _opts);
          if (result) {
            x = result;
            i = 0;
            return state = 'ROUTE';
          } else {
            i++;
            return state = 'TRY_MATCH';
          }
        } else {
          i = 0;
          x++;
          return state = 'ROUTE';
        }
      },
      WORD: function() {
        if (items[i]) {
          return state = 'TRY_MATCH';
        } else {
          x++;
          return state = 'ROUTE';
        }
      },
      NOTWORD: function() {
        x++;
        return state = 'ROUTE';
      },
      SELF_CLOSE: function() {
        state = 'ROUTE';
        return x++;
      },
      OPEN: function() {
        stack.push(xml[x]);
        state = 'ROUTE';
        return x++;
      },
      CLOSE: function() {
        stack.pop();
        state = 'ROUTE';
        return x++;
      },
      ROUTE: function() {
        if (x >= xml.length) {
          state = 'STOP';
          return;
        }
        if (isSelfClose(xml[x], opts.selfclose)) {
          state = 'SELF_CLOSE';
          return;
        }
        if (isOpen(xml[x])) {
          state = 'OPEN';
          return;
        }
        if (isClose(xml[x])) {
          state = 'CLOSE';
          return;
        }
        if (isWord(xml[x])) {
          state = 'WORD';
          return;
        }
        if (isntWord(xml[x])) {
          state = 'NOTWORD';
          return;
        }
        // should never happen, defensive
        x++;
      }
    };
    // when we're done, join all the XML bits to compute the result
    while (state !== 'STOP') {
      prev_state = state;
      if (FSM[state]) {
        FSM[state]();
      } else {
        console.log(state, " not implemented...");
        process.exit(0);
      }
    }
    return xml.join('');
  };

  tokenize_text = function(xml, selfclose) {
    var item, j, len, result;
    result = [];
    for (j = 0, len = xml.length; j < len; j++) {
      item = xml[j];
      if (isSelfClose(item, selfclose) || isOpen(item) || isClose(item)) {
        result.push(item);
      } else {
        result.push(...item.match(XRegExp("[[\\pL\\pN]+|[^\\pL\\pN]+", "g")));
      }
    }
    return result;
  };

  linkify = function(xml, items, opts) {
    opts || (opts = {});
    opts.allowed || (opts.allowed = ALLOWED_TAGS);
    opts.selfclose || (opts.selfclose = SELF_CLOSING_TAGS);
    opts.excluded || (opts.excluded = EXCLUDED_TAGS);
    xml = ShallowParse(xml);
    xml = tokenize_text(xml, opts.selfclose);
    return _linkify(xml, items, opts);
  };

  module.exports = linkify;

  module.exports.allowed = ALLOWED_TAGS;

  module.exports.selfclosing = SELF_CLOSING_TAGS;

  module.exports.excluded = EXCLUDED_TAGS;

}).call(this);
